In [1]:
import neuralnet as nn
import numpy as np

In [2]:
# read file and pre-process
with open("adult.data", "r") as f:
    lines = f.readlines()

df=[]
for i in lines:
    df.append(i.split(','))
df=df[:-1]
for i in range(len(df)):    
    if (df[i][1] ==' Private'):   ## workclass(1)
        df[i][1]=0
    elif (df[i][1]== ' Never-worked'):
        df[i][1]=2
    else:
        df[i][1]=1

    if (df[i][3] ==' Bachelors'):   ## education(3)
        df[i][3]=1
    elif (df[i][3]== ' Masters' or ' Doctorate'):
        df[i][3]=2
    else:
        df[i][3]=0

    if (df[i][5] ==' Never-married'):   ## marital-status(5)
        df[i][5]=0
    else:
        df[i][5]=1

    if (df[i][8] ==' White'):   ## race(8)
        df[i][8]=0
    elif (df[i][8]== ' Asian-Pac-Islander'):
        df[i][8]=1
    elif (df[i][8]== ' Amer-Indian-Eskimo'):
        df[i][8]=2
    elif (df[i][8]== ' Black'):
        df[i][8]=3
    else:
        df[i][8]=4
    
    if (df[i][9] ==' Male'):   ## sex(9)
        df[i][9]=1
    else:
        df[i][9]=0

    if (df[i][13] ==' United-States'):   ## native-country(13)
        df[i][13]=1
    else:
        df[i][13]=0

    if (df[i][14] ==' >50K\n'):   ## class(14)
        df[i][14]=1
    else:
        df[i][14]=0

for i in df:   ## delete occupation(6) && relationship(7)
    del i[6:8]  
    del i[2]

df = np.array([[int(j) for j in i] for i in df])

In [3]:
print(type(df), df.shape)
print(nn.normalize(df))

<class 'numpy.ndarray'> (32561, 12)
[[ 0  1 -2 ...  0  0  0]
 [ 0  1 -2 ... -2  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 1  0  0 ...  0  0  0]
 [-1  0  0 ... -1  0  0]
 [ 0  1  0 ...  0  0  1]]


In [4]:
split = 27000
df_train = df[:split]
df_test = df[split:]

In [29]:
model = nn.Network()
input_shape = df.shape[1]-1
model.construct_network(input_shape, [1,2])

In [32]:
print(model.net[0].weights)
#print(model.net[1].weights)

[[-0.34560532 -0.08880443 -0.94081387 -0.28074139 -0.47236345  0.29373946
   0.25529712  0.46958917 -0.19584196 -0.41596786 -0.9671897  -0.77915644]]


In [31]:
model.train(df_train, n_epoch=3, learning_rate=0.1, batch_size=100)

>epoch=1/3, loss=0.40309, time=-2.14293s/epoch
>epoch=2/3, loss=0.36632, time=-2.20534s/epoch
>epoch=3/3, loss=0.36599, time=-2.21408s/epoch
Training complete


In [33]:
model.test_model(df_test)

Result: 75.49% accuracy, 4198/5561 correct


0.7549001978061499

In [34]:
for i in range(10):
    model.forward_propagate(df_test[i,:-1])
    print(model.get_output())

[0.7310206 0.2689794]
[0.73664747 0.26335253]
[0.72362672 0.27637328]
[0.73941074 0.26058926]
[0.73612289 0.26387711]
[0.73529988 0.26470012]
[0.73334395 0.26665605]
[0.73708709 0.26291291]
[0.73831778 0.26168222]
[0.73064318 0.26935682]
